controllers/ResultController.php
<?php

namespace app\controllers;

use Yii;
use kartik\mpdf\Pdf;
use app\models\HasilPkl;
use app\models\ResultSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ResultController implements the CRUD actions for HasilPkl model.
 */
class ResultController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all HasilPkl models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $user = Yii::$app->user->identity;
        if ($user == ""){
            $this->layout ="login";
            if (!Yii::$app->user->isGuest) {
                return $this->goHome();
            }
        }
        
        $searchModel = new ResultSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single HasilPkl model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new HasilPkl model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new HasilPkl();
        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $model->end_pkl = date('Y-m-d', strtotime($model->end_pkl));
                $model->save();
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing HasilPkl model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post())) {
            
            $model->end_pkl = date('Y-m-d', strtotime($model->end_pkl));
            if($model->status == "daftar" || $model->status == ""){
                $model->end_pkl = null;
            }

            $post = $this->request->post();
            $p = $post["HasilPkl"];
            
            $nilaiRata = ($p["q1"] + $p["q2"]+ $p["q3"] + $p["q4"]+$p["q5"]+$p["q6"] + $p["q7"] + $p["q8"] + $p["q9"] + $p["q10"]) / 10;
            if ($nilaiRata > 85){
                $nilai_huruf = "A";
            }elseif ($nilaiRata < 85 && $nilaiRata > 70) {
                $nilai_huruf = "B";
            }elseif ($nilaiRata< 70 && $nilaiRata> 60) {
                $nilai_huruf = "C";
            }else{
                $nilai_huruf = "D";
            }
    
            if($nilaiRata < 60){
                $status = "Tidak Lulus";
            }else{
                $status = "Lulus";
            }

            $model->nilai = $nilaiRata;
            $model->nilai_huruf = $nilai_huruf;
            $model->status = $status;

            $model->save();
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }


    public function actionDownload($id)
    {
        $model = $this->findModel($id);
		return $this->render('_reportView', ['model'=>$model]);    
    }

    /**
     * Deletes an existing HasilPkl model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the HasilPkl model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return HasilPkl the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = HasilPkl::findOne(['id_result' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiswaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Siswa;
use app\models\HasilPkl;
use app\models\UnitBagian;
use app\models\DataSiswaPKL;
use app\models\SiswaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * SiswaController implements the CRUD actions for Siswa model.
 */
class SiswaController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                ],
            ]
        );
    }

    /**
     * Lists all Siswa models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new SiswaSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Siswa model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Siswa model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Siswa();
        $model["status"]  = "daftar";
        // $modelPKL = new DataSiswaPKL();
        
        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $model->file = UploadedFile::getInstance($model, 'file');
                $model["surat_pkl"] = $model->file->baseName . '.' . $model->file->extension;
                if ($model->upload() && $model->save()){
                    return $this->redirect(['view', 'id' => $model->id]);
                } 
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
            // 'modelPKL' =>$modelPKL,
        ]);
    }

    public function actionUpdateBagian($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            $request = $this->request->post();
            if($request["Siswa"]["unit_tugas"] != ""){
                $updateUnitBagian = UnitBagian::find()->where(['id_bagian'=>$request["Siswa"]["unit_tugas"]])->One();
                $av = $updateUnitBagian->available - 1;
                Yii::$app->db->createCommand('UPDATE unit_bagian SET available ='. $av .' WHERE id_bagian ='. $updateUnitBagian->id_bagian .' AND available > 0')->execute();
            }
            return $this->redirect(['view-unit-tugas', 'id' => $model->id]);
        }

        return $this->render('update_unit', [
            'model' => $model,
        ]);
    }
    
    public function actionUnit()
    {
        $searchModel = new SiswaSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('siswa_unit', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionStatus()
    {
        $searchModel = new SiswaSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('siswa_status', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionUpdateStatus($id)
    {
        $model = $this->findModel($id);
        if ($this->request->isPost && $model->load($this->request->post())) {
            $model->tgl_mulai_pkl = date('Y-m-d', strtotime($model->tgl_mulai_pkl));
            if($model->status == "daftar" || $model->status == ""){
                $model->tgl_mulai_pkl = null;
            }

            $model->save();

            $pkl = new HasilPkl();
            $pkl["start_pkl"]  = $model->tgl_mulai_pkl;
            $pkl["id_siswa"] = $model->id;
            $pkl->save();

            return $this->redirect(['status', 'id' => $model->id]);
        }

        return $this->render('update_status', [
            'model' => $model,
        ]);
    }

     /**
     * Displays a single Siswa model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionViewUnitTugas($id)
    {
        return $this->render('view_unit_tugas', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing Siswa model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Siswa model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Siswa model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Siswa the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Siswa::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/footer.php
<strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">Admin</a>.</strong>
All rights reserved.
<div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 3.2.0
</div>

views/layouts/header.php
<!-- Preloader -->
<!-- Navbar -->
<!-- Left navbar links -->
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
    </li>
</ul>
<!-- Right navbar links -->
<ul class="navbar-nav ml-auto">
    <!-- Navbar Search -->
    <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
            <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
            <form class="form-inline">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                        <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
            <i class="fas fa-expand-arrows-alt"></i>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
            <i class="fas fa-th-large"></i>
        </a>
    </li>
</ul>
<!-- /.navbar -->

views/layouts/leftbar.php
<?php
  use yii\helpers\Html;
  use yii\helpers\Url; 
  use app\models\User;
?>

<!-- Brand Logo -->
<a href="index3.html" class="brand-link">
<!-- <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8"> -->
    <?php echo Html::img('@web/image/usni.png', ['class' => 'brand-image img-circle elevation-3" style="opacity: .8']); ?>
    <span class="brand-text font-weight-light">Dashboard USNI</span>
</a>
<!-- Sidebar -->
<div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <!-- <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image"> -->
            <?php echo Html::img('@web/AdminLTE/dist/img/avatar.png', ['class' => 'img-circle elevation-2']); ?>
        </div>
        <div class="info">
            <?php $user = Yii::$app->user->identity; if ($user->status == 10): ?>

            <a href="#" class="d-block">              
                Hi, <?= $user->username; ?>
                <br>
                <?php
                    switch ($user->role) {
                        case 1:
                            echo "Super Admin";
                            break;
                        case 2:
                            echo "Hi, Purek";
                            break;
                        default:
                        echo "Hi, Admin";
                            break;
                    }
                ?>
            </a>
            <?php endif; ?>
        </div>
        </div>
        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                    <i class="fas fa-search fa-fw"></i>
                </button>
            </div>
        </div>
    </div>
    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
            with font-awesome or any other icon font library -->
        <li class="nav-item menu-open">
            <a href="<?=Url::to(['/'])?>" class="nav-link active">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                    Dashboard
                    <!-- <i class="right fas fa-angle-left"></i> -->
                </p>
            </a>
        </li>
        <?php 
            $user = Yii::$app->user->identity;   
            if($user->role == 2) :
        ?>
        <li class="nav-item">
        <a href="<?= Url::to(['siswa/status']) ?>" class="nav-link">
            <i class="nav-icon fas fa-book"></i>
            <p>
            <p>Approval Siswa PKL</p>
            </p>
        </a>
        </li>
        <?php endif; ?>
        <?php 
            $user = Yii::$app->user->identity;   
            if($user->role == 1 ||  $user->role == 3) :
        ?>
        <li class="nav-item">
        <a href="<?=Url::to(['siswa/index'])?>" class="nav-link">
            <i class="nav-icon fas fa-table"></i>
            <p>
                Daftar Siswa PKL
            </p>
        </a>
        </li>
        <?php endif; ?>
        <?php 
            $user = Yii::$app->user->identity;   
            if($user->role == 1) :
        ?>
        <li class="nav-item">
        <a href="<?= Url::to(['siswa/unit']) ?>" class="nav-link">
            <i class="nav-icon fas fa-book"></i>
            <p>
            <p>Pembagian Unit PKL</p>
            </p>
        </a>
        </li>
        <?php endif; ?>
        <?php 
            $user = Yii::$app->user->identity;   
            if($user->role == 1 ||  $user->role == 3) :
        ?>
        <li class="nav-item">
        <a href="<?=Url::to(['result/index'])?>" class="nav-link">
            <i class="nav-icon fas fa-edit"></i>
            <p>
                Hasil Siswa PKL
            </p>
        </a>
        </li>
        <?php endif; ?>
        <?php 
            $user = Yii::$app->user->identity;   
            if($user->role == 1) :
        ?>
        <li class="nav-item">
        <a href="<?=Url::to(['unit-bagian/index'])?>" class="nav-link">
            <i class="nav-icon fas fa-columns"></i>
            <p>
            Unit Bagian
            </p>
        </a>
        </li>
        <?php endif; ?>
        <?php 
            $user = Yii::$app->user->identity;   
            if($user->role == 1) :
        ?>
        <li class="nav-item">
        <a href="<?=Url::to(['user/index'])?>" class="nav-link">
            <i class="nav-icon fas fa-user"></i>
            <p> Users</p>
        </a>
        </li>
        <?php endif; ?>
        <li class="nav-header">Logout</li>
        <li class="nav-item">
        <a href="<?=Url::to(['site/logout']) ?>" class="nav-link">
            <i class="fas fa-circle nav-icon"></i>
            <p>Logout</p>
        </a>
        </li>
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>
<!-- /.sidebar -->

views/layouts/login.php
<?php

    /* @var $this \yii\web\View */
    /* @var $content string */

    use app\assets\LoginAsset;
    use yii\helpers\Html;
    use yii\bootstrap\Nav;
    use yii\bootstrap\NavBar;
    use yii\widgets\Breadcrumbs;
    use common\widgets\Alert;

    LoginAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition login-page">
<?php $this->beginBody() ?>
	<div class="login-box"> 
	    <?= $content ?>
	</div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title>Aplikasi Penilaian</title>
    <?php $this->head() ?>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<?php $this->beginBody() ?>
<div class="wrapper">
    <div class="preloader flex-column justify-content-center align-items-center">
        <!-- <img class="animation__shake" src="dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60"> -->
    </div>
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <?= $this->render('header')?>
    </nav>
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <?= $this->render('leftbar')?>
    </aside>
    <div class="content-wrapper">
        <!-- <section class="content"> -->
            <!-- page start-->
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= $content ?>
            <!-- page end-->
        <!-- </section> -->
    </div>
    <footer class="main-footer">
        <?= $this->render('footer')?>
    </footer>
    <aside class="control-sidebar control-sidebar-dark" style="display: none;">
        <?= $this->render('aside')?>
    </aside>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>